name: MLOps CI/CD Pipeline Serving

on:
  push:
    branches:
      - serving_pipelines

jobs:
  build_train_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    env:
      GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      GCP_REGION: ${{ vars.GCP_REGION }}
      GCP_ARTIFACT_REGISTRY_REPO: ${{ vars.GCP_ARTIFACT_REGISTRY_REPO }}
      GCP_VERTEX_BUCKET: ${{ vars.GCP_VERTEX_BUCKET }}
      GCP_SERVICE_ACCOUNT: ${{ vars.GCP_SERVICE_ACCOUNT }}

    outputs:
      MODEL_ID: ${{ steps.model_upload.outputs.MODEL_ID }}

      
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: "Configure Docker for Artifact Registry"
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: "Build and Push Serving Docker Image"
        run: |
          gsutil cp gs://${{ env.GCP_VERTEX_BUCKET }}/models/house-price-model/model.joblib model.joblib
          SERVING_IMAGE_TAG="${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_ARTIFACT_REGISTRY_REPO }}/house-price-predictor:latest"
          echo "Building Serving Docker image: ${SERVING_IMAGE_TAG}"
          docker build --platform linux/amd64 -f Dockerfile -t "${SERVING_IMAGE_TAG}" .
          echo "Pushing Serving Docker image: ${SERVING_IMAGE_TAG}"
          docker push "${SERVING_IMAGE_TAG}"

      - name: "Upload Model to Vertex AI Model Registry"
        id: model_upload
        run: |
          MODEL_ARTIFACT_URI="gs://${{ env.GCP_VERTEX_BUCKET }}/models/house-price-model/"
          SERVING_IMAGE_TAG="${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_ARTIFACT_REGISTRY_REPO }}/house-price-predictor:latest"

          echo "Uploading model to Vertex AI Model Registry..."
          gcloud ai models upload \
            --region=${{ env.GCP_REGION }} \
            --display-name="house-price-model-$(date +%Y%m%d%H%M%S)-crp" \
            --artifact-uri="${MODEL_ARTIFACT_URI}" \
            --container-image-uri="${SERVING_IMAGE_TAG}" \
            --format="value(name)"
          
          MODEL_ID=$(gcloud ai models list --region=${{ env.GCP_REGION }} --sort-by=~updateTime --limit=1 --format="value(name)" | cut -d '/' -f 6)

          echo "Model uploaded with ID: $MODEL_ID"
          cat <<EOF >> "${GITHUB_OUTPUT}"
          MODEL_ID=$MODEL_ID
          EOF

      - name: "Deploy Model to Endpoint"
        id: deploy_model
        run: |
          echo "Deploying model ${{ steps.model_upload.outputs.MODEL_ID }} to endpoint house-price-prediction-endpoint"
          gcloud ai endpoints deploy-model house-price-prediction-endpoint \
            --model=projects/${{ env.GCP_PROJECT_ID }}/locations/${{ env.GCP_REGION }}/models/${{ steps.model_upload.outputs.MODEL_ID }} \
            --display-name="house-price-deployment-$(date +%Y%m%d%H%M%S)" \
            --machine-type=n1-standard-2 \
            --min-replica-count=1 \
            --max-replica-count=1 \
            --traffic-split=0=100 \
            --region=${{ env.GCP_REGION }}
          echo "Model deployment initiated. This can take several minutes."
